# Generated by Django 2.0.13 on 2019-05-09 12:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GeoJSONSourceModel',
            fields=[
                ('sourcemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_geosource.SourceModel')),
                ('file', models.FileField(upload_to='geosource/')),
            ],
            bases=('django_geosource.sourcemodel',),
        ),
        migrations.CreateModel(
            name='PostGISSourceModel',
            fields=[
                ('sourcemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_geosource.SourceModel')),
                ('db_host', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='(?:(?:25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)(?:\\.(?:25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}|\\[[0-9a-f:\\.]+\\]|([a-z¡-\uffff0-9](?:[a-z¡-\uffff0-9-]{0,61}[a-z¡-\uffff0-9])?(?:\\.(?!-)[a-z¡-\uffff0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z¡-\uffff-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\.?|localhost))')])),
                ('db_username', models.CharField(max_length=63)),
                ('db_password', models.CharField(max_length=255)),
                ('db_name', models.CharField(max_length=63)),
            ],
            bases=('django_geosource.sourcemodel',),
        ),
    ]
