# Generated by Django 2.0.13 on 2019-05-09 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_geosource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geojsonsourcemodel',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='postgissourcemodel',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='sourcemodel',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='sourcemodel',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_django_geosource.sourcemodel_set+', to='contenttypes.ContentType'),
        ),
    ]
