# Generated by Django 2.0.13 on 2019-05-15 09:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_geosource.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_geosource', '0002_auto_20190509_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[(django_geosource.models.FieldTypes(1), 1), (django_geosource.models.FieldTypes(2), 2), (django_geosource.models.FieldTypes(3), 3), (django_geosource.models.FieldTypes(4), 4)], max_length=255)),
                ('sample', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
            ],
        ),
        migrations.AddField(
            model_name='postgissourcemodel',
            name='geom_field',
            field=models.CharField(default='geom', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postgissourcemodel',
            name='query',
            field=models.TextField(default='SELECT 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postgissourcemodel',
            name='refresh',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcemodel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sourcemodel',
            name='name',
            field=models.CharField(default='Default title', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcemodel',
            name='status',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='fieldmodel',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_geosource.SourceModel'),
        ),
    ]
