# Generated by Django 2.0.13 on 2019-05-15 14:31

from django.db import migrations, models
import django.db.models.deletion
import django_geosource.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_geosource', '0003_auto_20190515_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgissourcemodel',
            name='geom_type',
            field=models.IntegerField(choices=[(django_geosource.models.GeometryTypes(0), 0), (django_geosource.models.GeometryTypes(1), 1), (django_geosource.models.GeometryTypes(3), 3), (django_geosource.models.GeometryTypes(4), 4), (django_geosource.models.GeometryTypes(5), 5), (django_geosource.models.GeometryTypes(6), 6), (django_geosource.models.GeometryTypes(7), 7)], default=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldmodel',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='django_geosource.SourceModel'),
        ),
    ]
