# Generated by Django 2.0.13 on 2019-05-16 09:19

from django.db import migrations, models
import django_geosource.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_geosource', '0004_auto_20190515_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmodel',
            name='data_type',
            field=models.CharField(choices=[(1, django_geosource.models.FieldTypes(1)), (2, django_geosource.models.FieldTypes(2)), (3, django_geosource.models.FieldTypes(3)), (4, django_geosource.models.FieldTypes(4))], max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='fieldmodel',
            unique_together={('source', 'name')},
        ),
    ]
