# Generated by Django 2.1.9 on 2019-06-12 08:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("django_geosource", "0005_auto_20190603_1506")]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="sample",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        )
    ]
