# Generated by Django 2.0.13 on 2019-05-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_geosource', '0005_auto_20190516_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgissourcemodel',
            name='db_port',
            field=models.IntegerField(default=5432),
            preserve_default=False,
        ),
    ]
