# Generated by Django 2.0.13 on 2019-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_geosource', '0006_postgissourcemodel_db_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgissourcemodel',
            name='id_field',
            field=models.CharField(default='id', max_length=255),
        ),
    ]
