# Generated by Django 2.0.13 on 2019-05-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_geosource', '0008_auto_20190521_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgissourcemodel',
            name='id_field',
        ),
        migrations.AddField(
            model_name='sourcemodel',
            name='id_field',
            field=models.CharField(default='id', max_length=255),
        ),
    ]
