# Generated by Django 2.0.13 on 2019-06-28 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("django_geosource", "0009_source_slug")]

    operations = [
        migrations.CreateModel(
            name="WMTSSource",
            fields=[
                (
                    "source_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_geosource.Source",
                    ),
                ),
                ("minzoom", models.IntegerField(null=True)),
                ("maxzoom", models.IntegerField(null=True)),
                ("tile_size", models.IntegerField()),
                ("url", models.URLField()),
            ],
            options={"abstract": False, "base_manager_name": "objects"},
            bases=("django_geosource.source",),
        )
    ]
