# Generated by Django 2.0.13 on 2019-05-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_geosource', '0009_auto_20190521_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
