# Generated by Django 2.0.13 on 2019-05-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_geosource', '0010_auto_20190521_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgissourcemodel',
            name='db_port',
            field=models.IntegerField(default=5432),
        ),
    ]
