# Generated by Django 3.1.4 on 2021-09-08 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("django_geosource", "0020_auto_20201008_0851"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="last_refresh",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
