# Generated by Django 3.1.14 on 2022-03-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_geosource", "0021_source_last_refresh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="sample",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="postgissource",
            name="db_host",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="source",
            name="report",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="source",
            name="settings",
            field=models.JSONField(default=dict),
        ),
    ]
